"""empty message

Revision ID: 20c0082bd53b
Revises: properties
Create Date: 2022-03-09 10:17:36.813926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c0082bd53b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_title', sa.String(length=255), nullable=True),
    sa.Column('property_description', sa.String(length=255), nullable=True),
    sa.Column('noOfRooms', sa.Integer(), nullable=True),
    sa.Column('noOfBathrooms', sa.Integer(), nullable=True),
    sa.Column('property_price', sa.String(length=255), nullable=True),
    sa.Column('property_location', sa.String(length=255), nullable=True),
    sa.Column('property_type', sa.String(length=255), nullable=True),
    sa.Column('property_imgFilename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
